apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: argocd
spec:
  project: default

  source:
    # Replace with your GitHub repo URL after you push this project
    repoURL: https://github.com/YOUR_USERNAME/eks-argocd-practice.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: demo-app

  syncPolicy:
    automated:
      prune: true      # deletes resources removed from Git
      selfHeal: true    # reverts manual cluster changes back to Git state
    syncOptions:
      - CreateNamespace=true
